### ISSUE TITLE
[SC-2960] Disable Health Check endpoint by default

### ISSUE THREAD

**Issue by kylezs** [chainflip-io/chainflip-backend#1167]
## Description

The `/health` endpoint is only really to be used internally, and externally could just cause operators confusion. I think we should do something like:

## Solution
If health check config is present like: 
```toml
[health_check]
hostname = "0.0.0.0"
port = 5555
```

Then start the health check endpoint. Otherwise, don't start it at all.
