### ISSUE TITLE
Health check cannot be disabled

### ISSUE THREAD

**Issue by kylezs** [chainflip-io/chainflip-backend#2440]
### Description

The original intention of the health check was that we could enable it just for our testing environments (or whoever wants to enable it), but it doesn't need to be on to operate.

The way this is done is: 
- If the `[health_check]` settings are set in the Default.toml, then the health check will kick off
- If the `[health_check]` settings are not set (i.e. there's no `[health_check]` category), then the health check will not turn on.

The issue is that here:
```rust
if let Some(health_check_settings) = &settings.health_check {
                scope.spawn(HealthChecker::new(health_check_settings, &root_logger).await?.run());
            }
```
`health_check` is *always* Some.

I removed the `[health_check]` section from `Testing.toml` and then ran this test:

```rust

	#[tokio::test]
	async fn not_supplying_health_check_is_none() {
		let health_check = Settings::new_test().unwrap().health_check;

		println!("The health check is set: {:?}", health_check);
	}
```

The `Testing.toml`:
```toml
# Testing configurations for the CFE
[node_p2p]
node_key_file = "/run/secrets/node_key_file"
ip_address = "1.1.1.1"
port = 8087

[state_chain]
# 32 byte hex secret key - associated with the node's public id (public key)
signing_key_file = "./tests/test_keystore/alice_key"
ws_endpoint = "ws://localhost:9944"

[eth]
# Ethereum private key file path. Default is the docker secrets path. This file should contain a hex-encoded private key.
http_node_endpoint = "http://localhost:8545"
private_key_file = "/run/secrets/eth_private_key"
ws_node_endpoint = "ws://localhost:8545"

# [health_check]
# hostname = "127.0.0.1"
# port = 5555

[signing]
db_file = "data.db"
```

And I get:
```
The health check is set: Some(HealthCheck { hostname: "", port: 0 })
```

This should of course, return `None` instead.
