### ISSUE TITLE
Run Stake Manager Integration Test on CI

### ISSUE THREAD

**Issue by j4m1ef0rd** [chainflip-io/chainflip-backend#389]
Details for running the test are in this [readme](https://github.com/chainflip-io/chainflip-backend/blob/develop/engine/tests/README.md).
1) Run Nats and Ganache-cli
2) Run the [setup.sh](https://github.com/chainflip-io/chainflip-backend/blob/develop/engine/tests/scripts/setup.sh)
3) Run the Stake Manager integration test with cargo (more integration tests will also be ran here in the future)

I'm not sure how far kyle got on implementing this already. I have some code from the drone.yml that was left over from kyle's old branch from making the integration test. I don't know if it helps.

```
#  Runs all tests at night
kind: pipeline
type: kubernetes
name: chainflip-backend-nightly
environment:
  SCCACHE_REDIS: redis://drone-redis-headless:6379/
  SCCACHE_CACHE_SIZE: 14G
services:
  - image: trufflesuite/ganache-cli:latest
    name: ganache
    ports: [8545]
    entrypoint:
      - "node"
      - "/app/ganache-core.docker.cli.js"
      - "--mnemonic brownie"
      - "--gasLimit 12000000"
      - "--accounts 10"
      - "--hardfork istanbul"
  - image: nats:latest
    ports: [4222,8222]
    name: nats
steps:
  - name: stakemanager-events-setup
    image: ghcr.io/chainflip-io/chainflip-backend/rust-base:latest
    commands:
      - sh ./engine/tests/scripts/setup.sh
  - name: run-tests
    image: ghcr.io/chainflip-io/chainflip-backend/rust-base:latest
    commands:
      - cargo test --locked --release
# Config
trigger:
  event:
    - push
image_pull_secrets:
  - dockerconfigjson

```
